package main

import ( // docs is generated by Swag CLI, you have to import it.

	_ "HelloWorld/docs"
	"HelloWorld/handler"
	"HelloWorld/router"
	"github.com/iris-contrib/swagger"              // swagger middleware for Iris
	"github.com/iris-contrib/swagger/swaggerFiles" // swagger embed files
	"github.com/kataras/iris/v12"
	"github.com/kataras/iris/v12/middleware/logger"
	"github.com/kataras/iris/v12/middleware/recover"
)

// @title hello world 测试相关接口
// @version 1.0
// @description go 初步学习
// @termsOfService http://swagger.io/terms/

// @contact.name 豆豆
// @contact.url http://www.swagger.io/support
// @contact.email 951828649@qq.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host 这里写接口服务的host
// @BasePath 这里写base path
func main() {
	app := iris.New()
	app.Logger().SetLevel("debug")
	// 设置recover从panics恢复，设置log记录
	app.Use(recover.New())
	app.Use(logger.New())
	app.Use(handler.UserHandle)
	app.Get("/swagger/*any", swagger.Handler(swaggerFiles.Handler))

	router.RegisterUserRouter(app)
	router.RegisterRouterRouter(app)
	app.Run(iris.Addr(":8033"))
	//app.Run(iris.Server(&http.Server{Addr:":8033"}))

}
